language: node_js
node_js:
  - "12"
script:
  - ./bin/generate users -l 300 -o ./output
  # - echo 'dsti.adaltas.cloud' > output/CNAME
  # - pwd
  # - ls -l ./output
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  local-dir: output
  on:
    branch: master
env:
  global:
  - secure: "RN2QIUxwNa7yWM0B7LA2W+KUXronWsXwe6GZ4SkMLYUJ1BIMol+Bmq/UibeAAKcPe12wnzpcnG4Ww6EQ8YHukRNd6egzBSFblavt+b56Z/cSghykQat2QkPi3UsClyK+jV+7CMsxvvYOXAHngFGZ4Qlkmk2pTkyeZOV+FP/6yLHAJmyj4J/nE3+YucGv8Xq6Hv4b64W3RHB1aTVqokGsM9qdWx06haZwqU8YoKBpw+Acg0CoXS+piZm3vuqcArqu6g5zIigitgOJJ2dcRLTePE7xGgCqkxGmeXlFsU2i/VVcvrMCOD0tdHsrKKcivDKBbZJBUOAjU/jWKMRoKG3/U1NbRWO5ZLkkybkQUFXwk3FZBLULV3rQ5eDKlqnT0gPHLkDpfe3Nn6Lz91GjTDzajN8I/41kYByvTm8igkGxTDRd4QH/c58Qzfldn8qGfIfPitro+Q8yAcyRs5gRxIquzE7jY6LV64WRFQVjqG5DBZgkDedk++/RFPEqQMfe6V877zNNRZytN67RoscxyZObeAFj9oE9i861zmOg0dpBRL5Jdj/LQOKpEtXOYU4HJigwNhleLkfCIEX7y0Mou0CpTTCTpgdT2MBWhB0gm212NSUBARwVkTUp+3wvU2PK0UFA79canz7o0g58hEXiS4zsBXqKyWSJ1JAYJboe+lRORVw="
